### ISSUE TITLE
Improve feedback during long operations

### ISSUE THREAD

**Issue by cbuchart** [stt-systems/parallel_foreach_submodule#5]
The tool seems to print output only when all submodules have been processed, so on long operations it seems to be unresponsive. It would be nice to either:
- see output as it appears (probably when a thread finishes the execution of the command for a given submodule, so race conditions are reduced)
- or at least see a progress bar (number of submodules processed so far)

**Comment by RDCH106** [comment]
Each command executed in each submodule is printed when command has finished to prevent output mixing with other commands executed in other submodules in parallel. Maybe your computer is using resources in other processes and the terminal or console thread it is not refreshing the output properly.

About a type of progress bar it is not too difficult implement it. The problem it is the performance because of the atomic access to the counter variable. I will investigate this option.
